plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = "C:\\Users\\roblo\\OneDrive\\Documents\\Claude\\Projects\\chiclen little webpage"
publishOrigin = "default"
base = "C:\\Users\\roblo\\OneDrive\\Documents\\Claude\\Projects\\chiclen little webpage"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]